reorder_impl_items = true
reorder_imports = true
reorder_modules = true
group_imports = "StdExternalCrate"
imports_layout = "Vertical"
imports_granularity = "Crate"
binop_separator = "Front"
use_field_init_shorthand = true
